---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver_plugin: vagrant
  - name: digitalocean
    driver_plugin: digitalocean
    driver_config:
      region: nyc3
      size: 1gb
      image: ubuntu-14-04-x64
  - name: gce
    driver_plugin: gce
    driver_config:
      google_client_email: <%= ENV['GCE_CLIENT_EMAIL'] %>
      google_key_location: <%= ENV['GCE_ACCOUNT_FILE'] %>
      google_project: <%= ENV['GCE_PROJECT_ID'] %>
      region: us-central1-f
      image_name: ubuntu-1404-trusty-v20150128
  - name: ec2
    driver_plugin: ec2
    driver_config:
      aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
      aws_secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
      aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
      image_id: ami-f35078c3
      region: us-west-2
      availability_zone: us-west-2b
      flavor_id: c3.large
      username: ubuntu

suites:
  - name: default
    run_list:
      - recipe[octohost::default]
    attributes:
