language: ruby
cache: bundler
sudo: false
rvm:
  - 2.1.5
  - 2.2.0
install: bundle install
script: bundle exec rake test
branches:
  only:
  - master
notifications:
  slack:
    secure: fsHnbqcvrbRmPgDsxiJL4OJJ033FXpbdmT7cvG7HbBmWCQzZdoSMdbFCPdB8B1iITeO+c0++5Rszdd/+BG5YHjTTD4Qf8otFI0CVTYs0LxM7QlD05KrYCAiHcRipsp4LleaiH+4UxUrhRkstRz4i4NvXdwaspaLoW9tMroxr2aQ=
